#!/bin/bash

echo ""

echo "***************************** ENCODE *****************************"

echo ""

echo -n "STDIN:    " ; echo "Bonjour" | ./ft_ssl base64
echo -n "FILE:     " ; echo "Bonjour" | ./ft_ssl base64 -o tmp; cat tmp
echo -n "OUTPUT:   " ; echo "Bonjour" > tmp ; ./ft_ssl base64 -i tmp
echo -n "OPENSSL:  " ; echo "Bonjour" | base64

echo ""

echo -n "STDIN:    " ; echo "Salut" | ./ft_ssl base64 -e
echo -n "FILE:     " ; echo "Salut" | ./ft_ssl base64 -o tmp; cat tmp
echo -n "OUTPUT:   " ; echo "Salut" > tmp ; ./ft_ssl base64 -i tmp
echo -n "OPENSSL:  " ; echo "Salut" | base64

echo ""

echo -n "STDIN:    " ; echo "Saluta" | ./ft_ssl base64
echo -n "FILE:     " ; echo "Saluta" | ./ft_ssl base64 -o tmp; cat tmp
echo -n "OUTPUT:   " ; echo "Saluta" > tmp ; ./ft_ssl base64 -i tmp
echo -n "OPENSSL:  " ; echo "Saluta" | base64

echo ""

echo -n "STDIN:    " ; echo "" | ./ft_ssl base64 -e
echo -n "FILE:     " ; echo "" | ./ft_ssl base64 -o tmp; cat tmp
echo -n "OUTPUT:   " ; echo "" > tmp ; ./ft_ssl base64 -i tmp
echo -n "OPENSSL:  " ; echo "" | base64

echo ""

echo -n "STDIN:    " ; echo -n "" | ./ft_ssl base64
echo ""
echo -n "FILE:     " ; echo -n "" | ./ft_ssl base64 -o tmp; cat tmp;
echo ""
echo -n "OUTPUT:   " ; echo -n "" > tmp ; ./ft_ssl base64 -i tmp; rm tmp
echo ""
echo -n "OPENSSL:  " ; echo -n "" | base64
echo ""

echo ""

echo "******************************************************************"

echo ""

echo "***************************** DECODE *****************************"

echo ""

echo -n "STDIN:    " ; echo "Qm9uam91cgo=" | ./ft_ssl base64 -d
echo -n "FILE:     " ; echo "Qm9uam91cgo=" | ./ft_ssl base64 -o tmp -d; cat tmp;
echo -n "OUTPUT:   " ; echo "Qm9uam91cgo=" > tmp ; cat tmp | ./ft_ssl base64 -i tmp -d;
echo -n "OPENSSL:  " ; echo "Qm9uam91cgo=" | base64 -d

echo ""

echo -n "STDIN:    " ; echo "U2FsdXQK" | ./ft_ssl base64 -d
echo -n "FILE:     " ; echo "U2FsdXQK" | ./ft_ssl base64 -o tmp -d; cat tmp;
echo -n "OUTPUT:   " ; echo "U2FsdXQK" > tmp ; cat tmp | ./ft_ssl base64 -i tmp -d;
echo -n "OPENSSL:  " ; echo "U2FsdXQK" | base64 -d

echo ""

echo -n "STDIN:    " ; echo "U2FsdXRhCg==" | ./ft_ssl base64 -d
echo -n "FILE:     " ; echo "U2FsdXRhCg==" | ./ft_ssl base64 -o tmp -d; cat tmp;
echo -n "OUTPUT:   " ; echo "U2FsdXRhCg==" > tmp ; cat tmp | ./ft_ssl base64 -i tmp -d;
echo -n "OPENSSL:  " ; echo "U2FsdXRhCg==" | base64 -d

echo ""

echo -n "STDIN:    " ; echo "" | ./ft_ssl base64 -d
echo ""
echo -n "FILE:     " ; echo "" | ./ft_ssl base64 -o tmp -d; cat tmp;
echo ""
echo -n "OUTPUT:   " ; echo "" > tmp ; cat tmp | ./ft_ssl base64 -i tmp -d;
echo ""
echo -n "OPENSSL:  " ; echo "" | base64 -d
echo ""

echo ""

echo -n "STDIN:    " ; echo -n "" | ./ft_ssl base64 -d
echo ""
echo -n "FILE:     " ; echo -n "" | ./ft_ssl base64 -o tmp -d; cat tmp;
echo ""
echo -n "OUTPUT:   " ; echo -n "" > tmp ; cat tmp | ./ft_ssl base64 -i tmp -d;
echo ""
echo -n "OPENSSL:  " ; echo -n "" | base64 -d
echo ""

echo ""

echo "******************************************************************"

echo ""

echo "******************************* ERROR ****************************"

echo ""

echo "U2FsdX" | ./ft_ssl base64 -d
echo ""
echo "U2FsdX" | base64 -d
echo ""

echo ""

echo "AB#" | ./ft_ssl base64 -d
echo "AB#" | base64 -d

echo ""

echo "******************************************************************"

echo ""

echo "****************************** TRICKY ****************************"

echo ""

echo "ABCR" > tmp;
cat tmp | openssl base64 -d
echo ""
cat tmp | ./ft_ssl base64 -d; rm tmp
echo ""

echo "CCC" | ./ft_ssl base64 -d
echo "CCC" | base64 -d
echo ""

python -c 'print("\x00\x00\x00\x00")' | base64 -d
python -c 'print("\x00\x00\x00\x00")' | ./ft_ssl base64 -d

python -c 'print("\xFF\x00\x00\x00")' | base64 -d
python -c 'print("\xFF\x00\x00\x00")' | ./ft_ssl base64 -d

python -c 'print("\x00\xFF\x00\x00")' | base64 -d
python -c 'print("\x00\xFF\x00\x00")' | ./ft_ssl base64 -d

python -c 'print("\x0A\x00\xFF\x00")' | base64 -d
python -c 'print("\x0A\x00\xFF\x00")' | base64 -d
echo ""

python -c 'print("\x0A\x0A\xFF\x00")' | ./ft_ssl base64 -d
python -c 'print("\x0A\x0A\xFF\x00")' | ./ft_ssl base64 -d

echo ""

echo "******************************************************************"

echo ""
