#!/bin/bash

# Is BASE64 working?
#echo "repeat after me 'encoding is not encryption'" | base64
#echo "repeat after me 'encoding is not encryption'" | ./ft_ssl base64
#diff <(echo -n abc | openssl base64) <(echo -n abc | ./ft_ssl base64)
#echo "All your base are belong to us. You have no chance make your time." | ./ft_ssl base64 | ./ft_ssl base64 -d


# Do they have a flag in their base?
#echo "best game in the franchise" | ./ft_ssl base64 -e -o "halo1" 
#./ft_ssl base64 -d -i "halo1"


# DES-eptively easy!
#export DES_KEY="C0FFEE69DEADBEEF"
#echo "foo bar" | ./ft_ssl des-ecb -k "$DES_KEY" | openssl des-ecb -d -K "$DES_KEY"
#echo "foo bar" | openssl des-ecb -K "$DES_KEY" | ./ft_ssl des-ecb -d -k "$DES_KEY"
#echo "smol" | ./ft_ssl des-ecb -k "$DES_KEY" | openssl des-ecb -d -K "$DES_KEY"
#echo "smol" | openssl des-ecb -K "$DES_KEY" | ./ft_ssl des-ecb -d -k "$DES_KEY"
#echo "testing the key now" | openssl des-ecb -K "ABCD" | ./ft_ssl des-ecb -d -k "ABCD"
#echo "More key tests" | openssl des-ecb -K "FFFFFFFFFFFFFFFF" | ./ft_ssl des-ecb -d -k "FFFFFFFFFFFFFFFF"
#echo "what kind of lock takes no key?" | openssl des-ecb -K "00000000" | ./ft_ssl des-ecb -d -k "00000000"


# YOU SHALL NOT PASS(word)!
#echo "$(curl 'https://www.peereboom.us/assl/assl/html/openssl.html')" > original.html
#echo "password" > password_file
#openssl des-ecb -p -in original.html -out ciphertext.html -pass "pass:$(cat password_file)"
#./ft_ssl des-ecb -d -i ciphertext.html -o decrypted.html -p "$(cat password_file)" -s 5A25980E077444B9 #(Copy the salt used by OpenSSL here!)
#open *.html
#rm ciphertext.html decrypted.html original.html password_file


# Are they on the Cipher BlockChain?
#echo "Make sure they really tell you what is going on 'under the hood' when you use CBC mode, and how it is more secure than ECB" | openssl des-cbc -K "BABE101010FACADE" -iv "77696E6B66616365" | ./ft_ssl des-cbc -k "BABE101010FACADE" -v "77696E6B66616365" -d