#!/bin/bash

echo "********************************* EMPTY *********************************"
echo -n "FILE:    "
./ft_ssl sha256 -q ./test/file/empty
echo -n "STRING:  "
cat ./test/file/empty | ./ft_ssl sha256 -q
echo -n "STDOUT:  "
./ft_ssl sha256 -q -s ""
echo -n "OPENSSL: "
./test/file/empty | openssl sha256
echo "*************************************************************************"

echo ""

echo "************************** LESS THAN 56 BYTES ***************************"
echo -n "FILE:    "
./ft_ssl sha256 -q ./test/file/less_than_56
echo -n "STRING:  "
cat ./test/file/less_than_56 | ./ft_ssl sha256
echo -n "STDOUT:  "
./ft_ssl sha256 -q -s "abcdefghijabcdefghijabcdefghij"
echo -n "OPENSSL: "
cat ./test/file/less_than_56 | openssl sha256
echo "*************************************************************************"

echo ""

echo "************************* BETWEEN 56 & 64 BYTES *************************"
echo -n "FILE:    "
./ft_ssl sha256 -q ./test/file/between_56_\&_64
echo -n "STRING:  "
cat ./test/file/between_56_\&_64 | ./ft_ssl sha256 -q
echo -n "STDOUT:  "
./ft_ssl sha256 -q -s "123456789
123456789
123456789
123456789
123456789
123456789
1234"
echo -n "OPENSSL: "
cat ./test/file/between_56_\&_64 | openssl sha256
echo "*************************************************************************"

echo ""

echo "************************** MORE THAN 64 BYTES ***************************"
echo -n "FILE:    "
./ft_ssl sha256 -q ./test/file/more_than_64
echo -n "STRING:  "
cat ./test/file/more_than_64 | ./ft_ssl sha256 -q
echo -n "STDOUT:  "
./ft_ssl sha256 -q -s "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij
abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij
abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij
abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij
abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij"
echo -n "OPENSSL: "
cat ./test/file/more_than_64 | openssl sha256
echo "*************************************************************************"

echo ""

echo "********************************** BIG **********************************"
echo -n "FILE:    "
./ft_ssl sha256 -q ./test/file/big
echo -n "STDOUT:  "
cat ./test/file/big | ./ft_ssl sha256
echo -n "OPENSSL: "
cat ./test/file/big | openssl sha256
echo "*************************************************************************"