#!/bin/bash

echo ""
echo ""

echo "echo \"https://www.youtube.com/watch?v=w-5yAtMtrSM\" > big_smoke_order_remix"
echo "./ft_ssl sha256 -q big_smoke_order_remix"
echo "a8dc621c3dcf18a8a2eddae1845e8e5f6498970a867056ac5f7121ac3d66cfd9"
echo "https://www.youtube.com/watch?v=w-5yAtMtrSM" > big_smoke_order_remix
./ft_ssl sha256 -q big_smoke_order_remix

echo ""
echo ""

echo "./ft_ssl sha256 big_smoke_order_remix"
echo "SHA256 (big_smoke_order_remix) = a8dc621c3dcf18a8a2eddae1845e8e5f6498970a867056ac5f7121ac3d66cfd9"
./ft_ssl sha256 big_smoke_order_remix

echo ""
echo ""

echo "./ft_ssl sha256 -s \"wubba lubba dub dub\""
echo "SHA256 (\"wubba lubba dub dub\") = 23a0944d11b5a54f1970492b5265c732044ae824b7d5656acb193e7f0e51e5fa"
./ft_ssl sha256 -s "wubba lubba dub dub"

echo ""
echo ""

rm big_smoke_order_remix

