#!/usr/bin/env python3

import calcul
import tools

def ft_linear_regression():
    data            = tools.parse_csv()
    #normalized_data = tools.normalize_data(data)
    normalized_data = {}
    normalized_data['km'] = tools.mean_normalization(data['km'])
    normalized_data['price'] = tools.mean_normalization(data['price'])
    normalized_data['m'] = len(data['km'])

    t0, t1          = calcul.gradient_descent(normalized_data, 0.1, 10000)
    print("\n")
    print(t0, t1)

    t0 = t0 * max(data['price'])
    t1 = t1 * (max(data['price']) / max(data['km']))

    print(t0, t1)
    #print('Cost: ' + str(calcul.cost_function(t0, t1, normalized_data)))
    #print(calcul.least_squares(t0, t1, normalized_data))
    #print(round(t0, 3))

ft_linear_regression()