#!/usr/bin/env python3

import calcul
import tools
import plot

def ft_linear_regression():
    data                                          = tools.parse_csv()
    normalized_data                               = calcul.min_max_normalization(data)
    t0, t1, cost_history, accuracy, curve_history = calcul.gradient_descent(data, normalized_data, 0.1, 1000)

    plot.launch_animation(data, curve_history, accuracy, cost_history)

ft_linear_regression()