#!/usr/bin/env python3

import sys
import argparse
import srcs.tools as tools
import srcs.calcul as calcul
import srcs.parsing as parsing
import srcs.display as display
import srcs.Constant as Constant

def set_argparse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='describe dataset features', type=tools.is_valid_dataset)
    parser.parse_args()

def describe():
    set_argparse()

    CONST             = Constant.Const()
    dataset           = parsing.get_dataset_by_features(sys.argv[1], CONST.FEATURES_NAME[1:], 1)
    described_dataset = calcul.describe_dataset(dataset, CONST.FEATURES_NAME[1:], CONST.ROWS_FUNCTION)

    display.print_described_dataset(described_dataset, CONST.FEATURES_NAME[1:], CONST.ROWS_FUNCTION.keys())

if __name__ == '__main__':
    describe()
