#!/usr/bin/env python3

import sys
import parsing
import tools

FEATURES_NAME = [
               'Arithmancy',
               'Astronomy',
               'Herbology',
               'Defense Against the Dark Arts',
               'Divination',
               'Muggle Studies',
               'Ancient Runes',
               'History of Magic',
               'Transfiguration',
               'Potions',
               'Care of Magical Creatures',
               'Charms',
               'Flying'
           ]

OPERATIONS_NAME = [
                      'Count',
                      'Mean',
                      'Std',
                      'Min',
                      '25%',
                      '50%',
                      '75%',
                      'Max'
                  ]

def describe():
    return 0

describe()