#!/usr/bin/env python3

import argparse
import srcs.plot as plot
import srcs.tools as tools
import srcs.parsing as parsing
import srcs.Constant as Constant

def set_argParse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='dataset', type=tools.is_train_dataset)
    return parser.parse_args()

def histogram():
    set_argParse()

    CONST                = Constant.Const()
    data_sorted_by_house = parsing.get_dataset_sorted_by_house('datasets/dataset_train.csv', CONST.FEATURES_NAME, CONST.HOUSES_NAME)

    plot.histogram(data_sorted_by_house, CONST)

if __name__ == '__main__':
    histogram()