#!/usr/bin/env python3

import argparse
import srcs.plot as plot
import srcs.tools as tools
import srcs.parsing as parsing
import srcs.Constant as Constant

def set_argParse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='dataset', type=tools.is_train_dataset)
    parser.add_argument('-d', '--demo', help='show histogram for every features.', action='store_true')
    return parser.parse_args()

def histogram():
    args = set_argParse()

    CONST                = Constant.Const()
    dataset_by_houses = parsing.get_dataset_by_houses('datasets/dataset_train.csv', CONST.FEATURES_NAME, CONST.HOUSES_NAME)

    plot.histogram(dataset_by_houses, CONST) if not args.demo else plot.histogram_demo(dataset_by_houses, CONST)

if __name__ == '__main__':
    histogram()