#!/usr/bin/env python3

import sys
import parsing
import tools
import calcul
import display
import argparse
import matplotlib.pyplot as plt
import numpy as np

def test():
    X = np.array([[1,2], [3,4], [5,6], [7,8]])
    T = np.zeros(X.shape[1])
    Y = np.array([1,1,0,0])
    

    T = calcul.gradient_descent(X, Y, 0.1, 2)
    #cost = cost_function(X, Y, activated) / X.shape[0]

    print(T)

if __name__ == '__main__':
    test()