#!/usr/bin/env python3

import sys
import argparse
import numpy as np
import srcs.tools as tools
import srcs.calcul as calcul
import srcs.display as display
import srcs.parsing as parsing
import matplotlib.pyplot as plt

def test():
    X = np.array([[1,2], [3,4], [5,6], [7,8]])
    T = np.zeros(X.shape[1])
    Y = np.array([1,1,0,0])
    

    T = calcul.gradient_descent(X, Y, 0.1, 2)
    #cost = cost_function(X, Y, activated) / X.shape[0]

    print(T)

if __name__ == '__main__':
    test()