#!/usr/bin/env python3

import sys
import argparse
import srcs.plot as plot
import srcs.tools as tools
import srcs.parsing as parsing
import srcs.Constant as Constant

def set_argParse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='dataset', type=tools.is_train_dataset)
    parser.add_argument('-d', '--demo', help='show pair plot for every features.', action='store_true')
    return parser.parse_args()

def pair_plot():
    args    = set_argParse()
    CONST   = Constant.Const()
    dataset = parsing.get_dataset(sys.argv[1], CONST.FEATURES_NAME, 2)

    plot.pair_plot(dataset, CONST) if not args.demo else plot.pair_plot_demo(dataset, CONST)

if __name__ == '__main__':
    pair_plot()
