#!/usr/bin/env python3

import sys
import parsing
import tools
import calcul
import display
import argparse
import matplotlib.pyplot as plt

FEATURES_NAME = [
                    'Hogwarts House',
                    'Arithmancy',
                    'Astronomy',
                    'Herbology',
                    'Defense Against the Dark Arts',
                    'Divination',
                    'Muggle Studies',
                    'Ancient Runes',
                    'History of Magic',
                    'Transfiguration',
                    'Potions',
                    'Care of Magical Creatures',
                    'Charms',
                    'Flying'
                ]

HOUSES_NAME = {
                  'Slytherin',
                  'Gryffindor',                
                  'Ravenclaw',                
                  'Hufflepuff'                
              }

def set_argParse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='describe dataset features', type=tools.check_dataset_name)
    return parser.parse_args()

def display_histogram(data_sorted_by_house):
    for house_name in HOUSES_NAME:
        plt.hist(data_sorted_by_house[house_name]['Charms'], bins=tools.count(data_sorted_by_house[house_name]['Charms']))
    plt.tick_params(axis='x', which='both', bottom=False, top=False, labelbottom=False)
    plt.xlabel('Charms')
    plt.show()

def plot():
    set_argParse()

    data_sorted_by_house = parsing.get_dataset_sorted_by_house('datasets/dataset_train.csv', FEATURES_NAME, HOUSES_NAME)

    display_histogram(data_sorted_by_house)

plot()