#!/usr/bin/env python3

import sys
import argparse
import srcs.plot as plot
import srcs.tools as tools
import srcs.parsing as parsing
import srcs.Constant as Constant

def set_argParse():
    parser = argparse.ArgumentParser()

    parser.add_argument('dataset.csv', help='dataset', type=tools.is_valid_dataset)
    parser.add_argument('-d', '--demo', help='show relations between features.', action='store_true')
    return parser.parse_args()

def scatter_plot():
    args    = set_argParse()
    CONST   = Constant.Const()
    dataset = parsing.get_dataset_by_features(sys.argv[1], CONST.FEATURES_NAME[1:], 1)

    plot.scatter(dataset) if not args.demo else plot.scatter_demo(dataset, CONST.FEATURES_NAME[1:])

if __name__ == '__main__':
    scatter_plot()
