# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: loiberti <marvin@le-101.fr>                +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2018/10/03 12:49:27 by loiberti     #+#   ##    ##    #+#        #
#    Updated: 2018/10/09 13:03:40 by loiberti    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

NAME = libft.a

CC = gcc

CFlAGS = -Wall -Wextra -Werror

SRC = ./ft_lstiter.c \
		./ft_putendl_fd.c \
		./ft_strequ.c \
		./ft_sort_integer_table.c \
		./ft_strrchr.c \
		./ft_lstmap.c \
		./ft_putnbr.c \
		./ft_striter.c \
		./ft_strrev.c \
		./ft_atoi.c \
		./ft_lstnew.c \
		./ft_putnbr_fd.c \
		./ft_striteri.c \
		./ft_strsplit.c \
		./ft_bzero.c \
		./ft_memalloc.c \
		./ft_putstr.c \
		./ft_strjoin.c \
		./ft_strstr.c \
		./ft_isalnum.c \
		./ft_memccpy.c \
		./ft_putstr_fd.c \
		./ft_strlcat.c \
		./ft_strsub.c \
		./ft_isalpha.c \
		./ft_memchr.c \
		./ft_recursive_power.c \
		./ft_strlen.c \
		./ft_strtrim.c \
		./ft_isascii.c \
		./ft_memcmp.c \
		./ft_strcapitalize.c \
		./ft_strmap.c \
		./ft_strupcase.c \
		./ft_isdigit.c \
		./ft_memcpy.c \
		./ft_strcat.c \
		./ft_strmapi.c \
		./ft_swap.c \
		./ft_isprint.c \
		./ft_memdel.c \
		./ft_strchr.c \
		./ft_strncat.c \
		./ft_tolower.c \
		./ft_itoa.c \
		./ft_memmove.c \
		./ft_strclr.c \
		./ft_strncmp.c \
		./ft_toupper.c \
		./ft_lowercase.c \
		./ft_memset.c \
		./ft_strcmp.c \
		./ft_strncpy.c \
		./ft_lstadd.c \
		./ft_putchar.c \
		./ft_strcpy.c \
		./ft_strnequ.c \
		./ft_lstdel.c \
		./ft_putchar_fd.c \
		./ft_strdel.c \
		./ft_strnew.c \
		./ft_lstdelone.c \
		./ft_putendl.c \
		./ft_strdup.c \
		./ft_strnstr.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	@ ar rcs $@ $?

clean:
	@ /bin/rm -f $(OBJ)

fclean: clean
	@ /bin/rm -f $(NAME)

re: fclean all
